"""

Revision ID: 9c96d58054df
Revises: 7ecbf63d1880
Create Date: 2024-06-09 21:03:57.335574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c96d58054df'
down_revision: Union[str, None] = '7ecbf63d1880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('page_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'page_count')
    # ### end Alembic commands ###
