"""

Revision ID: d6df904c1813
Revises: b5f7c72ef779
Create Date: 2024-06-12 00:03:20.274810

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6df904c1813'
down_revision: Union[str, None] = 'b5f7c72ef779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'reserves', 'booked_at', existing_type=postgresql.TIMESTAMP(), type_=sa.Date(), existing_nullable=False
    )
    op.alter_column(
        'reserves', 'due_date', existing_type=postgresql.TIMESTAMP(), type_=sa.Date(), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'reserves', 'due_date', existing_type=sa.Date(), type_=postgresql.TIMESTAMP(), existing_nullable=False
    )
    op.alter_column(
        'reserves', 'booked_at', existing_type=sa.Date(), type_=postgresql.TIMESTAMP(), existing_nullable=False
    )
    # ### end Alembic commands ###
