exclude: migrations
default_stages: [commit]
fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-ast
    - id: end-of-file-fixer
    - id: double-quote-string-fixer


- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
    - id: black
      args: [--config=app/pyproject.toml]


- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.8
  hooks:
    - id: ruff
      args: [--fix, --exit-zero]
    - id: ruff-format

default_language_version:
  python: python3.11
